import { learningModes } from '../src/scripts/sample-activities.js';
import { basicsDifferentiationTopic } from '../src/scripts/topic-content/basics-differentiation.js';
import { createPolynomialFunctionDefinition, niceYAxisTickStep, parsePolynomialExpression } from '../src/scripts/linked-function-gradient-explorer.js';
import fs from 'node:fs';

function assert(condition, message) { if (!condition) throw new Error(message); }
const understand = learningModes.understand.activities;
assert(understand.length === 7, 'The audited Basics journey should expose seven mathematical Understand activities after removing the redundant backstory page.');
const expected = basicsDifferentiationTopic.activities.filter((activity) => activity.mode === 'understand' && activity.implementationStep === 33).map((activity) => activity.activityId);
assert(JSON.stringify(understand.map((activity) => activity.activityId)) === JSON.stringify(expected), 'Understand order must match Step 32 canonical metadata.');
assert(understand.every((activity) => activity.basicsUnderstand === true), 'Every Step 33 Understand activity should opt into the shared custom experience.');

const polynomial = createPolynomialFunctionDefinition({ id:'check', label:'x^3-3x', coefficients:[0,-3,0,1] });
assert(polynomial.evaluate(2) === 2, 'Polynomial helper should preserve ascending coefficient convention.');
assert(polynomial.derivative(2) === 9, 'Derivative helper should remain mathematically correct for Step 33 explorer reuse.');
const typed=parsePolynomialExpression('3x^4 - 2x + 7');
const typedDefinition=createPolynomialFunctionDefinition({id:'typed-check',label:typed.canonicalText,coefficients:typed.coefficients});
assert(typedDefinition.evaluate(2)===51,'Typed polynomial coefficients must feed the shared function evaluator correctly.');
assert(typedDefinition.derivative(2)===94,'Typed polynomial coefficients must feed the shared derivative evaluator correctly.');
assert(niceYAxisTickStep([-38,38])===10,'Large polynomial y-ranges should use sparse readable y-axis labels.');
assert(niceYAxisTickStep([-8,8])===2,'Ordinary y-ranges should retain useful axis detail.');

const source=fs.readFileSync(new URL('../src/scripts/basics-understand.js',import.meta.url),'utf8');
const shellSource=fs.readFileSync(new URL('../src/scripts/app-shell.js',import.meta.url),'utf8');
const cssSource=fs.readFileSync(new URL('../src/styles/basics-understand.css',import.meta.url),'utf8');
assert(source.includes('Type a polynomial'),'Basics polynomial explorer must expose a typed expression field.');
assert(source.includes('parsePolynomialExpression'),'Typed entry must use the shared safe polynomial parser.');
assert(source.includes('maxDegree: 6'),'Typed entry must retain the reasonable-degree guard.');
assert(source.includes('aria-invalid'),'Invalid typed expressions must be reported accessibly.');
assert(source.includes('Or edit the coefficients'),'Coefficient controls must remain as a synchronized fallback.');
assert(source.includes("dataset.basicsActivity"),'Basics Understand must expose the current activity to the responsive single-screen layout.');
assert(source.includes('basics-understand__coefficient-details'),'The polynomial coefficient fallback should be collapsed by default so the graph remains the primary desktop workspace.');
assert(source.includes("'x⁶'"),'Coefficient fallback must remain synchronized through the maximum supported degree.');
assert(source.includes('Show gradient') && source.includes('Hide gradient'),'Gradient-on-curve feedback must use an explicit reveal toggle.');
assert(source.includes('basics-understand__gradient-popin'),'Gradient-on-curve feedback must be embedded as an in-graph pop-in.');
assert(source.includes('sidebarHost'),'Basics Understand must support moving tangent-activity controls into the teaching column.');
assert(shellSource.includes('sidebarHost: activityCopy'),'AppShell must provide the left activity-copy column to Basics Understand.');
assert(cssSource.includes('.basics-understand__gradient-popin') && cssSource.includes('position:absolute'),'The gradient pop-in must overlay the graph rather than consume a separate row.');
assert(cssSource.includes('curve_tangent_gradient') && cssSource.includes('.linked-gradient-explorer__controls { display:none; }'),'The tangent activity should remove the redundant explorer toolbar from the graph area.');
assert(source.includes("data-math-display"),'Derivative-notation equivalences must opt into the shared mathematics renderer.');
assert(source.includes('Newton and Leibniz developed calculus independently'),'Derivative notation should include the planned Newton–Leibniz historical explanation.');
assert(source.includes("vocab:d-dx-operator") && source.includes("renderVocabulary"),'Operator notation must be wired into the shared Word Bank renderer.');
assert(source.includes("vocab:f-prime-notation") && source.includes("vocab:dy-dx-notation"),'All three derivative notation families should connect to canonical vocabulary terms.');
assert(cssSource.includes('basics-understand__notation-story'),'The notation history anecdote needs a compact single-screen presentation.');
assert(source.includes("basics-understand__graph-card-tools--function") && source.includes("Plot this gradient point"),'Gradient-function plotting control must live inside the function graph card.');
assert(source.includes("basics-understand__graph-card-tools--derivative") && source.includes("Reveal complete f′(x)"),'Derivative reveal control must live inside the derivative graph card.');
assert(source.includes("derivativeExpression.hidden = true"),'The derivative rule must stay hidden until the student reveals the complete derivative.');
assert(source.includes("xReadout") && source.includes("functionReadout"),'The live x and f(x) values must be relocated into the function graph card.');
assert(cssSource.includes('gradient_function') && cssSource.includes('.linked-gradient-explorer__controls { display:none; }'),'Activity 3 must remove the redundant top explorer toolbar for a single-screen layout.');
assert(source.includes("basics-understand__operator-equation"),'The d/dx operator activity must use one direct equation rather than the old machine layout.');
assert(source.includes("operator, selectWrap, equals, output"),'The d/dx activity must read left-to-right as d/dx, selected expression, equals, derivative.');
assert(!source.includes("const inputBox = el(this.document, 'div', 'basics-understand__machine-box')"),'The old duplicated input box must be removed from the d/dx activity.');
assert(!source.includes("const arrow = el(this.document, 'div', 'basics-understand__machine-arrow', '→')"),'The old machine arrow must not be used in the d/dx activity.');
assert(cssSource.includes('.basics-understand__operator-select') && cssSource.includes('.basics-understand__operator-result'),'The rebuilt operator equation needs dedicated inline selection and result styling.');
assert(source.includes('We will explore how this rule works in a moment.'),'The d/dx operator activity must explicitly bridge forward to the power-rule explanation.');
assert(source.includes("basics-understand__pattern-equals") && source.includes("el(this.document, 'span', 'basics-understand__pattern-equals', '=')"),'Power-rule examples must use equality symbols rather than transformation arrows.');
assert(source.includes("basics-understand__power-rule-bubble") && source.includes("GENERAL RULE"),'The revealed power rule must have its own prominent labelled bubble.');
assert(source.includes("basics-understand__rule-coefficient") && source.includes("basics-understand__rule-power") && source.includes("basics-understand__rule-variable"),'The general rule must visually distinguish coefficient, power and variable roles.');
assert(source.includes('The old power multiplies the coefficient, then the power decreases by 1.'),'The key power-rule notice must appear beneath the revealed rule.');
assert(source.includes('basics-understand__term-map'),'Term-by-term differentiation must use a vertically aligned interactive term map.');
assert(source.includes("classList.toggle('is-active', active)"),'Hover, focus and selection must highlight each source/derivative pair together.');
assert(source.includes("node.addEventListener('pointerenter', enter)") && source.includes("node.addEventListener('focus', enter)"),'Term mapping must support both hover and keyboard focus.');
assert(source.includes("node.addEventListener('click', toggleLock)"),'Term mapping must provide a tap/click alternative that locks a highlighted pair.');
assert(source.includes("basics-understand__term-connector-arrow") && source.includes("'↓'"),'Each polynomial term must connect vertically to its derivative with a downward arrow.');
assert(cssSource.includes('.basics-understand__term-map') && cssSource.includes('.basics-understand__term-connector.is-active'),'Interactive term mapping needs aligned grid and highlighted connector styling.');
assert(cssSource.includes('.basics-understand__pattern-card') && cssSource.includes('.basics-understand__pattern-answer'),'Power-rule examples need a deliberate card-and-answer visual hierarchy.');
assert(cssSource.includes('.basics-understand__rule-coefficient') && cssSource.includes('.basics-understand__rule-power') && cssSource.includes('.basics-understand__rule-variable'),'The power-rule roles need distinct colour styling.');
assert(cssSource.includes('.basics-understand__power-rule-notice'),'The revealed rule needs a prominent explanatory notice underneath.');
assert(shellSource.includes('dataset.basicsUnderstandActive'),'AppShell must expose a Basics-only layout state instead of relying on a stale CSS selector.');
assert(cssSource.includes('container-name: basics-understand') && cssSource.includes('@container basics-understand'),'Basics Understand must respond to its actual visual-column width.');
assert(cssSource.includes('height: 100% !important'),'Basics Understand must override the generic natural-height Understand rule on desktop.');
assert(cssSource.includes('polynomial_explorer') && cssSource.includes('.basics-understand__coefficient-details[open]'),'The polynomial coefficient editor must expand in flow instead of being clipped.');
assert(cssSource.includes('grid-template-areas:') && cssSource.includes('"operator choice equals"'),'The d/dx operator must reflow when its visual container narrows.');
assert(cssSource.includes('min-width: 620px'),'Term-by-term algebra must preserve readable term widths rather than compressing until terms collide.');

assert(!understand.some((activity) => activity.activityId.endsWith(':calculus-backstory')),'The duplicated calculus-backstory activity must stay removed now that its content lives on derivative notation.');
console.log('PASS Basics Understand seven-state audited journey and linked polynomial contract');
