import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { differentialEquationsTopic, differentialEquationsVocabularyTags } from '../src/scripts/topic-content/differential-equations.js';
import { RATE_TRANSLATION_EXAMPLES, SEPARATION_EXAMPLES, INTEGRATED_EXAMPLES, isSeparatedForm, combineArbitraryConstants } from '../src/scripts/differential-equations-data.js';
import { INTEGRATION_METHOD_TAGS } from '../src/scripts/integration-method-vocabulary.js';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
assert.equal(differentialEquationsTopic.topicId,'topic:y13:differential-equations:first-order');
assert.ok(differentialEquationsTopic.modes.includes('understand'),'Step 72 Understand mode must remain available.');
const step72Activities=differentialEquationsTopic.activities.filter(a=>a.implementationStep===72);
assert.equal(step72Activities.length,6,'The six Step 72 Understand activities must remain intact.');
assert.ok(step72Activities.every(a=>a.mode==='understand'));

for(const tag of ['vocab:differential-equation','vocab:first-order','vocab:separable','vocab:general-solution','vocab:particular-solution','vocab:initial-condition']) assert.ok(differentialEquationsVocabularyTags.includes(tag));
assert.equal(RATE_TRANSLATION_EXAMPLES.find(x=>x.id==='decay-y').equation,'dy/dx = −ky');
assert.equal(RATE_TRANSLATION_EXAMPLES.find(x=>x.id==='inverse-square').equation,'dy/dx = k/x²');
assert.ok(SEPARATION_EXAMPLES.some(x=>!x.separable&&x.equation.includes('x + y')),'A non-separable near-miss is required.');
for(const x of SEPARATION_EXAMPLES.filter(x=>x.separable)) assert.equal(isSeparatedForm(x.separated),true,`${x.id} should end in a valid separated form.`);
assert.equal(combineArbitraryConstants(),'C₂ − C₁ = C');
assert.ok(INTEGRATED_EXAMPLES.every(x=>x.methodTags.every(t=>Object.values(INTEGRATION_METHOD_TAGS).includes(t))),'Post-separation integration must reuse the canonical Step 71 vocabulary.');
assert.ok(INTEGRATED_EXAMPLES.every(x=>x.methodTags.includes(INTEGRATION_METHOD_TAGS.standard)));
const understand=fs.readFileSync(path.join(root,'src/scripts/differential-equations-understand.js'),'utf8');
assert.match(understand,/createFamilyOfCurvesExplorer/,'Step 72 must reuse FamilyOfCurvesExplorer.');
assert.match(understand,/renderEquationSteps/,'Step 72 must reuse EquationStepRenderer.');
assert.match(understand,/STOP HERE/,'Step 72 requires a separation-only stopping point.');
assert.match(understand,/Step 73 will practise applying conditions/,'The original Step 72 boundary note should remain in the Understand explanation.');
assert.doesNotMatch(understand,/createElementNS|<svg|canvas/i,'Step 72 must not create a parallel graph engine.');
const shell=fs.readFileSync(path.join(root,'src/scripts/app-shell.js'),'utf8');
assert.match(shell,/topic:y13:differential-equations:first-order/);
assert.match(shell,/availableModes: Object\.freeze\(\[\.\.\.learningModeOrder\]\)/,'Step 73 may extend the topic to later modes without changing the Step 72 Understand experience.');
const html=fs.readFileSync(path.join(root,'src/index.html'),'utf8');
assert.match(html,/data-topic-id="topic:y13:differential-equations:first-order"/);
console.log('Differential equations Step 72 tests passed.');
