import assert from 'node:assert/strict';
import fs from 'node:fs';
import { parametricAreaTopic } from '../src/scripts/topic-content/parametric-area.js';
import { parametricAreaLearningModes } from '../src/scripts/parametric-area-activities.js';
import { PARAMETRIC_AREA_METHOD_TAG, PARAMETRIC_AREA_TRACER_SOURCE, PARAMETRIC_AREA_CASES, PARAMETRIC_AREA_CURVES, calculateThinStripState } from '../src/scripts/parametric-area-data.js';
import { PARAMETRIC_CURVES } from '../src/scripts/parametric-curve-tracer.js';
import { INTEGRATION_METHOD_TAGS } from '../src/scripts/trig-integration-data.js';
import { parametricAreaAssessmentQuestionDefinitions } from '../src/scripts/question-definitions/parametric-area-assessment.js';
import { getQuestionSetDefinitionForActivity } from '../src/scripts/question-catalogue.js';
import { getMemoryItemsForTopic } from '../src/scripts/memory-content.js';
import { getMemoryGamePackForTopic } from '../src/scripts/memory-game-content.js';
import { getMemoryReviewPackForTopic } from '../src/scripts/memory-review-content.js';
assert.equal(parametricAreaTopic.topicId,'topic:y13:integration:parametric-area');
assert.equal(parametricAreaTopic.sequence,340);
assert.deepEqual(parametricAreaTopic.modes,['understand','memorise','ao1','ao2','ao3']);
assert.ok(parametricAreaTopic.activities.filter(a=>a.implementationStep===68).length>=20);
for(const mode of parametricAreaTopic.modes) assert.ok(parametricAreaLearningModes[mode].activities.length>0,`${mode} should have activities`);
assert.strictEqual(PARAMETRIC_AREA_TRACER_SOURCE,PARAMETRIC_CURVES,'Step 68 must extend/reuse the ParametricCurveTracer source by reference');
assert.strictEqual(PARAMETRIC_AREA_METHOD_TAG,INTEGRATION_METHOD_TAGS.parametricArea);
assert.equal(INTEGRATION_METHOD_TAGS.parametricArea,'parametric-area');
const positive=PARAMETRIC_AREA_CURVES.find(c=>c.id==='parametric-area-positive');
const strip=calculateThinStripState(positive,1,.05);
assert.equal(strip.dxdt,1); assert.ok(strip.stripAreaApprox>0); assert.equal(strip.direction,'x increasing');
const ellipse=PARAMETRIC_AREA_CURVES.find(c=>c.id==='parametric-area-ellipse');
const left=calculateThinStripState(ellipse,Math.PI/2,.05); assert.ok(left.dxdt<0); assert.equal(left.direction,'x decreasing'); assert.ok(left.integrand<0);
assert.ok(PARAMETRIC_AREA_CASES.some(c=>c.id==='negative-dxdt'&&c.signed===true));
assert.ok(PARAMETRIC_AREA_CASES.some(c=>c.id==='geometric-ellipse'&&c.tLimits.includes('π to t=0')));
for(const method of ['trig-identity','substitution','integration-by-parts']) assert.ok(PARAMETRIC_AREA_CASES.some(c=>c.laterMethod===method),`missing later technique ${method}`);
assert.equal(parametricAreaAssessmentQuestionDefinitions.length,7);
for(const def of parametricAreaAssessmentQuestionDefinitions) assert.ok(['ao1','ao2','ao3'].includes(def.assessmentObjective));
for(const id of parametricAreaTopic.activities.filter(a=>a.activityType==='question-set').map(a=>a.activityId)) assert.ok(getQuestionSetDefinitionForActivity(id),`question set missing for ${id}`);
assert.ok(getMemoryItemsForTopic(parametricAreaTopic.topicId).length>=5);
assert.ok(getMemoryGamePackForTopic(parametricAreaTopic.topicId)?.sort);
assert.ok(getMemoryReviewPackForTopic(parametricAreaTopic.topicId)?.mix);
const tracer=fs.readFileSync(new URL('../src/scripts/parametric-curve-tracer.js',import.meta.url),'utf8');
assert.match(tracer,/showAreaTeachingOverlay/); assert.match(tracer,/y·dx\/dt/); assert.match(tracer,/x direction/);
const understand=fs.readFileSync(new URL('../src/scripts/parametric-area-understand.js',import.meta.url),'utf8');
assert.match(understand,/new ParametricCurveTracer/); assert.match(understand,/showAreaTeachingOverlay:true/); assert.match(understand,/Increasing t travels right → left/); assert.match(understand,/Parametric setup first, later technique second/);
const index=fs.readFileSync(new URL('../src/index.html',import.meta.url),'utf8');
assert.match(index,/topic:y13:integration:parametric-area/); assert.match(index,/parametric-area-understand\.css/);
console.log('Step 68 parametric-area contracts passed.');
