import assert from 'node:assert/strict';
import fs from 'node:fs';
import { partialFractionsIntegrationTopic } from '../src/scripts/topic-content/partial-fractions-integration.js';
import { partialFractionsLearningModes } from '../src/scripts/partial-fractions-activities.js';
import { PARTIAL_FRACTION_STRUCTURES, PARTIAL_FRACTION_EXAMPLES, STANDARD_INTEGRAL_PARTIAL_FRACTIONS_SOURCE, PARTIAL_FRACTIONS_METHOD_TAG, LOG_LAWS } from '../src/scripts/partial-fractions-data.js';
import { STANDARD_INTEGRAL_DEFINITIONS } from '../src/scripts/standard-integrals-data.js';
import { INTEGRATION_METHOD_TAGS } from '../src/scripts/trig-integration-data.js';
import { buildLinearDecomposition, solveTwoDistinctLinear, solveRepeatedSquare, verifyTwoDistinct, verifyRepeatedSquare, isProperRational } from '../src/scripts/partial-fractions-model.js';
import { partialFractionsAssessmentQuestionDefinitions } from '../src/scripts/question-definitions/partial-fractions-assessment.js';
import { getQuestionSetDefinitionForActivity } from '../src/scripts/question-catalogue.js';
import { getMemoryItemsForTopic } from '../src/scripts/memory-content.js';
import { getMemoryGamePackForTopic } from '../src/scripts/memory-game-content.js';
import { getMemoryReviewPackForTopic } from '../src/scripts/memory-review-content.js';

assert.equal(partialFractionsIntegrationTopic.topicId,'topic:y13:integration:partial-fractions');
assert.equal(partialFractionsIntegrationTopic.sequence,320);
assert.deepEqual(partialFractionsIntegrationTopic.modes,['understand','memorise','ao1','ao2','ao3']);
assert.equal(partialFractionsIntegrationTopic.activities.filter(a=>a.implementationStep===66).length,23);
for(const mode of partialFractionsIntegrationTopic.modes) assert.ok(partialFractionsLearningModes[mode].activities.length>0,`${mode} should have activities`);
assert.equal(INTEGRATION_METHOD_TAGS.partialFractions,'partial-fractions');
assert.equal(PARTIAL_FRACTIONS_METHOD_TAG,'partial-fractions');
assert.strictEqual(STANDARD_INTEGRAL_PARTIAL_FRACTIONS_SOURCE,STANDARD_INTEGRAL_DEFINITIONS,'Step 66 must reuse Step 60 standard-integral data by reference');
assert.ok(PARTIAL_FRACTION_STRUCTURES.some(x=>x.id==='distinct-three'));
assert.ok(PARTIAL_FRACTION_STRUCTURES.some(x=>x.id==='repeated-two'&&x.decomposition.includes('²')));
assert.ok(PARTIAL_FRACTION_STRUCTURES.some(x=>x.id==='improper'));
assert.equal(isProperRational({numeratorDegree:1,denominatorDegree:2}),true);
assert.equal(isProperRational({numeratorDegree:2,denominatorDegree:2}),false);
assert.deepEqual(buildLinearDecomposition([{label:'x−1',power:2}]),['A/(x−1)','B/(x−1)^2']);
const distinct=solveTwoDistinctLinear({a:1,b:-2,p:5,q:1});
assert.deepEqual(distinct,{A:2,B:3});
assert.equal(verifyTwoDistinct({a:1,b:-2,p:5,q:1,...distinct}),true);
const repeated=solveRepeatedSquare({a:1,p:3,q:5});
assert.deepEqual(repeated,{A:3,B:8});
assert.equal(verifyRepeatedSquare({a:1,p:3,q:5,...repeated}),true);
assert.match(PARTIAL_FRACTION_EXAMPLES.find(x=>x.id==='repeated').integrated,/− 8\/\(x−1\)/,'Repeated-factor term should use the power rule rather than a second log');
assert.equal(PARTIAL_FRACTION_EXAMPLES.find(x=>x.id==='improper').division,'1 + 3/((x+1)(x+2))');
assert.equal(PARTIAL_FRACTION_EXAMPLES.find(x=>x.id==='definite').singleLog,'3ln(4/3)');
assert.ok(LOG_LAWS.some(x=>x.id==='constant'&&x.right.includes('K>0')));
assert.equal(partialFractionsAssessmentQuestionDefinitions.length,9);
for(const def of partialFractionsAssessmentQuestionDefinitions){assert.ok(def.methodTags.includes('partial-fractions'));assert.ok(['ao1','ao2','ao3'].includes(def.assessmentObjective));}
for(const id of partialFractionsIntegrationTopic.activities.filter(a=>a.activityType==='question-set').map(a=>a.activityId)) assert.ok(getQuestionSetDefinitionForActivity(id),`question set missing for ${id}`);
assert.ok(getMemoryItemsForTopic(partialFractionsIntegrationTopic.topicId).length>=10);
assert.ok(getMemoryGamePackForTopic(partialFractionsIntegrationTopic.topicId)?.sort);
assert.ok(getMemoryReviewPackForTopic(partialFractionsIntegrationTopic.topicId)?.mix);
const index=fs.readFileSync(new URL('../src/index.html',import.meta.url),'utf8');
assert.match(index,/topic:y13:integration:partial-fractions/);
assert.match(index,/partial-fractions-understand\.css/);
const partsData=fs.readFileSync(new URL('../src/scripts/integration-by-parts-data.js',import.meta.url),'utf8');
assert.match(partsData,/id:'partial-fractions'/,'Method-positioning flow should now include partial fractions before parts');
console.log('Step 66 partial-fractions integration contracts passed.');
