import assert from 'node:assert/strict';
import fs from 'node:fs';
import { stationaryPointsTopic } from '../src/scripts/topic-content/stationary-points.js';
import { stationaryPointsLearningModes } from '../src/scripts/stationary-points-activities.js';
import { classifyDerivativeSigns, stationaryPointModel } from '../src/scripts/stationary-points-understand.js';
import { createPolynomialFunctionDefinition } from '../src/scripts/linked-function-gradient-explorer.js';

const expected=['zero-gradient','max-min-signs','stationary-inflection','classify-from-signs','second-derivative'];
assert.deepEqual(stationaryPointsLearningModes.understand.activities.map(a=>a.activityId),expected.map(s=>`activity:y12:differentiation:stationary-points:understand:${s}`));
assert.deepEqual(stationaryPointsTopic.modes,['understand','memorise','ao1','ao2','ao3']);
const step41Activities=stationaryPointsTopic.activities.filter(a=>a.mode==='understand');
assert.equal(step41Activities.length,5);
assert.ok(step41Activities.every(a=>a.implementationStep===41));
assert.ok(step41Activities.every(a=>a.route===`/y12/differentiation/stationary-points/understand/${a.slug}`));
assert.equal(classifyDerivativeSigns(1,-1),'local maximum');
assert.equal(classifyDerivativeSigns(-1,1),'local minimum');
assert.equal(classifyDerivativeSigns(1,1),'stationary point with no turn');
assert.equal(classifyDerivativeSigns(-1,-1),'stationary point with no turn');
const cubic=createPolynomialFunctionDefinition({id:'test-cubic',label:'x^3',coefficients:[0,0,0,1],xDomain:[-2,2]});
const cm=stationaryPointModel(cubic,0,0.25);
assert.equal(cm.pattern,'+→0→+');
assert.equal(cm.classification,'stationary point with no turn');
assert.equal(cm.secondDerivative,0);
assert.equal(cm.secondDerivativeConclusion,'inconclusive');
const min=createPolynomialFunctionDefinition({id:'test-min',label:'x^2',coefficients:[0,0,1],xDomain:[-2,2]});
const max=createPolynomialFunctionDefinition({id:'test-max',label:'-x^2',coefficients:[0,0,-1],xDomain:[-2,2]});
assert.equal(stationaryPointModel(min).secondDerivativeConclusion,'local minimum');
assert.equal(stationaryPointModel(max).secondDerivativeConclusion,'local maximum');
const source=fs.readFileSync(new URL('../src/scripts/stationary-points-understand.js',import.meta.url),'utf8');
assert.match(source,/createLinkedFunctionGradientExplorer/);
assert.doesNotMatch(source,/createElementNS\s*\(/);
const app=fs.readFileSync(new URL('../src/scripts/app-shell.js',import.meta.url),'utf8');
assert.match(app,/topic:y12:differentiation:stationary-points/);
assert.match(app,/topic:y12:differentiation:stationary-points/);
const html=fs.readFileSync(new URL('../src/index.html',import.meta.url),'utf8');
assert.match(html,/stationary-points-understand\.css/);
console.log('Step 41 stationary-points Understand contract passed.');
