import assert from 'node:assert/strict';
import fs from 'node:fs';
import { year13AreasTopic } from '../src/scripts/topic-content/year13-areas.js';
import { year13AreasLearningModes } from '../src/scripts/year13-areas-activities.js';
import { YEAR13_AREA_CASES, AREA_EXPLORER_SOURCE, AREA_METHOD_TAGS } from '../src/scripts/year13-areas-data.js';
import { INTEGRATION_AREA_POSITIVE_FUNCTIONS } from '../src/scripts/integration-area-model.js';
import { INTEGRATION_METHOD_TAGS } from '../src/scripts/trig-integration-data.js';
import { year13AreasAssessmentQuestionDefinitions } from '../src/scripts/question-definitions/year13-areas-assessment.js';
import { getQuestionSetDefinitionForActivity } from '../src/scripts/question-catalogue.js';
import { getMemoryItemsForTopic } from '../src/scripts/memory-content.js';
import { getMemoryGamePackForTopic } from '../src/scripts/memory-game-content.js';
import { getMemoryReviewPackForTopic } from '../src/scripts/memory-review-content.js';
assert.equal(year13AreasTopic.topicId,'topic:y13:integration:areas');
assert.equal(year13AreasTopic.sequence,330);
assert.deepEqual(year13AreasTopic.modes,['understand','memorise','ao1','ao2','ao3']);
assert.ok(year13AreasTopic.activities.filter(a=>a.implementationStep===67).length>=19);
for(const mode of year13AreasTopic.modes) assert.ok(year13AreasLearningModes[mode].activities.length>0,`${mode} should have activities`);
assert.strictEqual(AREA_EXPLORER_SOURCE,INTEGRATION_AREA_POSITIVE_FUNCTIONS,'Step 67 must reuse the Step 27/46 AreaExplorer function-definition source by reference');
assert.strictEqual(AREA_METHOD_TAGS,INTEGRATION_METHOD_TAGS,'Step 67 must reuse the canonical integration method vocabulary by reference');
for(const tag of ['standard-integral','reverse-chain','trig-identity','substitution','integration-by-parts','partial-fractions']) assert.ok(YEAR13_AREA_CASES.some(x=>x.method===tag),`Missing area case for ${tag}`);
assert.ok(YEAR13_AREA_CASES.some(x=>x.split===true),'A split-order case is required');
assert.ok(YEAR13_AREA_CASES.some(x=>x.geometry===true),'A geometry-vs-calculus case is required');
assert.equal(year13AreasAssessmentQuestionDefinitions.length,7);
for(const def of year13AreasAssessmentQuestionDefinitions) assert.ok(['ao1','ao2','ao3'].includes(def.assessmentObjective));
for(const id of year13AreasTopic.activities.filter(a=>a.activityType==='question-set').map(a=>a.activityId)) assert.ok(getQuestionSetDefinitionForActivity(id),`question set missing for ${id}`);
assert.ok(getMemoryItemsForTopic(year13AreasTopic.topicId).length>=4);
assert.ok(getMemoryGamePackForTopic(year13AreasTopic.topicId)?.sort);
assert.ok(getMemoryReviewPackForTopic(year13AreasTopic.topicId)?.mix);
const understand=fs.readFileSync(new URL('../src/scripts/year13-areas-understand.js',import.meta.url),'utf8');
assert.match(understand,/createAreaExplorer/,'Step 67 must reuse AreaExplorer rather than create a new area canvas');
assert.match(understand,/Required area = area under A − area under B/);
assert.match(understand,/Only now choose an integration method/);
const index=fs.readFileSync(new URL('../src/index.html',import.meta.url),'utf8');
assert.match(index,/topic:y13:integration:areas/);
assert.match(index,/year13-areas\.css/);
console.log('Step 67 Year 13 area-technique contracts passed.');
