import { defineTopicMetadata } from '../topic-metadata.js';
const prefix='y13:integration:substitution';
const skill=s=>`skill:${prefix}:${s}`; const activity=(s,m='understand')=>`activity:${prefix}:${m}:${s}`;
export const substitutionVocabularyTags=Object.freeze(['vocab:integration','vocab:integrand','vocab:substitution','vocab:differential','vocab:definite-integral','vocab:chain-rule']);
export const substitutionTopic=defineTopicMetadata({
  topicId:`topic:${prefix}`,scopeId:'y13-additional',strand:'integration',slug:'substitution',title:'Integration by substitution',sequence:300,
  modes:['understand','memorise','ao1','ao2','ao3'],prerequisiteTopicIds:['topic:y13:integration:reverse-chain-rule'],prerequisiteTags:['reverse-chain','standard-integrals'],vocabularyTags:substitutionVocabularyTags,
  journey:[
    {id:'why',title:'See why substitution works',summary:'Compare fast reverse-chain recognition with the systematic variable-change route on the same integral.',microSkillIds:[skill('recognition-comparison')],vocabularyTags:['vocab:substitution','vocab:chain-rule']},
    {id:'change-everything',title:'Change everything to the new variable',summary:'Transform the integrand and differential together, rejecting mixed-variable states.',microSkillIds:[skill('transform-integrand'),skill('mixed-variable-check'),skill('given-substitution'),skill('error-diagnosis')],vocabularyTags:['vocab:differential','vocab:integrand']},
    {id:'definite-indefinite',title:'Separate indefinite and definite workflows',summary:'Substitute back for indefinite integrals; change limits and stay in u for definite integrals.',microSkillIds:[skill('indefinite-workflow'),skill('definite-limits')],vocabularyTags:['vocab:definite-integral']},
    {id:'choose-u',title:'Choose a substitution that makes progress',summary:'Look inside powers, roots, exponentials, trig, logs, denominators and repeated expressions, then check whether the derivative is available.',microSkillIds:[skill('choose-u'),skill('judge-substitution'),skill('applications')],vocabularyTags:['vocab:substitution']},
    {id:'diagnose',title:'Diagnose the failed stage',summary:'Separate a poor choice of u from an incomplete transformation or a later integration error.',microSkillIds:[skill('error-diagnosis')],vocabularyTags:['vocab:substitution','vocab:differential']},
    {id:'apply',title:'Use substitution when it is not signposted',summary:'Select and carry out substitution in unfamiliar indefinite and definite applications.',microSkillIds:[skill('applications')],vocabularyTags:['vocab:definite-integral']}
  ],
  microSkills:[
    {microSkillId:skill('recognition-comparison'),slug:'recognition-comparison',title:'Compare reverse-chain recognition with systematic substitution',prerequisiteTags:['reverse-chain'],vocabularyTags:['vocab:substitution','vocab:chain-rule'],supportTargets:{understand:activity('why-substitution'),memorise:activity('method-position','memorise'),ao2:activity('compare-recognition','ao2')}},
    {microSkillId:skill('transform-integrand'),slug:'transform-integrand',title:'Transform the integrand and differential completely into u',prerequisiteTags:['reverse-chain'],vocabularyTags:['vocab:differential','vocab:integrand'],supportTargets:{understand:activity('change-everything'),memorise:activity('change-everything','memorise'),ao1:activity('given-substitution','ao1')}},
    {microSkillId:skill('mixed-variable-check'),slug:'mixed-variable-check',title:'Detect and reject mixed x/u variable states',prerequisiteTags:['reverse-chain'],vocabularyTags:['vocab:differential'],supportTargets:{understand:activity('change-everything'),memorise:activity('mixed-variable-check','memorise'),ao2:activity('diagnose-errors','ao2')}},
    {microSkillId:skill('given-substitution'),slug:'given-substitution',title:'Carry out a supplied substitution consistently',prerequisiteTags:['reverse-chain'],vocabularyTags:['vocab:substitution','vocab:differential'],supportTargets:{understand:activity('change-everything'),ao1:activity('given-substitution','ao1')}},
    {microSkillId:skill('indefinite-workflow'),slug:'indefinite-workflow',title:'Complete an indefinite substitution and return to x with +C',prerequisiteTags:['standard-integrals'],vocabularyTags:['vocab:substitution'],supportTargets:{understand:activity('definite-indefinite'),memorise:activity('finish-rules','memorise'),ao1:activity('complete-substitution','ao1')}},
    {microSkillId:skill('definite-limits'),slug:'definite-limits',title:'Write x-limits first, convert them to u-limits and stay in u',prerequisiteTags:['definite-integral'],vocabularyTags:['vocab:definite-integral'],supportTargets:{understand:activity('definite-indefinite'),memorise:activity('limit-conversion','memorise'),ao1:activity('change-limits','ao1')}},
    {microSkillId:skill('choose-u'),slug:'choose-u',title:'Choose a useful inner or repeated expression as u',prerequisiteTags:['reverse-chain'],vocabularyTags:['vocab:substitution'],supportTargets:{understand:activity('choosing-u'),memorise:activity('choose-u-cues','memorise'),ao1:activity('choose-u','ao1')}},
    {microSkillId:skill('judge-substitution'),slug:'judge-substitution',title:'Explain why a proposed substitution helps or fails',prerequisiteTags:['reverse-chain'],vocabularyTags:['vocab:substitution'],supportTargets:{understand:activity('choosing-u'),ao2:activity('diagnose-errors','ao2')}},
    {microSkillId:skill('error-diagnosis'),slug:'error-diagnosis',title:'Distinguish choice, transformation and integration errors',prerequisiteTags:['reverse-chain','standard-integrals'],vocabularyTags:substitutionVocabularyTags,supportTargets:{understand:activity('change-everything'),ao2:activity('diagnose-errors','ao2')}},
    {microSkillId:skill('applications'),slug:'applications',title:'Apply substitution in unfamiliar contexts',prerequisiteTags:['definite-integral','standard-integrals'],vocabularyTags:substitutionVocabularyTags,supportTargets:{understand:activity('choosing-u'),ao3:activity('unfamiliar-applications','ao3')}}
  ],
  activities:[
    {activityId:activity('why-substitution'),mode:'understand',slug:'why-substitution',title:'Why substitution?',activityType:'interactive',microSkillIds:[skill('recognition-comparison')],vocabularyTags:substitutionVocabularyTags,implementationStep:63},
    {activityId:activity('change-everything'),mode:'understand',slug:'change-everything',title:'Change everything to u',activityType:'interactive',microSkillIds:[skill('transform-integrand'),skill('mixed-variable-check'),skill('given-substitution'),skill('error-diagnosis')],vocabularyTags:substitutionVocabularyTags,implementationStep:63},
    {activityId:activity('definite-indefinite'),mode:'understand',slug:'definite-indefinite',title:'Indefinite vs definite',activityType:'interactive',microSkillIds:[skill('indefinite-workflow'),skill('definite-limits')],vocabularyTags:substitutionVocabularyTags,implementationStep:63},
    {activityId:activity('choosing-u'),mode:'understand',slug:'choosing-u',title:'Choosing u',activityType:'interactive',microSkillIds:[skill('choose-u'),skill('judge-substitution'),skill('applications')],vocabularyTags:substitutionVocabularyTags,implementationStep:63},
    ...['method-position','change-everything','choose-u-cues','limit-conversion','finish-rules','mixed-variable-check','memory-games','mixed-review'].map((slug,i)=>({activityId:activity(slug,'memorise'),mode:'memorise',slug,title:['Recognition or substitution?','Change-everything sequence','Choosing u cues','Changing definite limits','How to finish','Mixed-variable check','Memory games','Mixed review'][i],activityType:'memory',microSkillIds:[skill(i===0?'recognition-comparison':i===1?'transform-integrand':i===2?'choose-u':i===3?'definite-limits':i===4?'indefinite-workflow':i===5?'mixed-variable-check':'choose-u')],vocabularyTags:substitutionVocabularyTags,implementationStep:64})),
    {activityId:activity('given-substitution','ao1'),mode:'ao1',slug:'given-substitution',title:'Carry out a given substitution',activityType:'question-set',microSkillIds:[skill('given-substitution'),skill('transform-integrand')],vocabularyTags:substitutionVocabularyTags,implementationStep:64},
    {activityId:activity('choose-u','ao1'),mode:'ao1',slug:'choose-u',title:'Choose u',activityType:'question-set',microSkillIds:[skill('choose-u')],vocabularyTags:substitutionVocabularyTags,implementationStep:64},
    {activityId:activity('change-limits','ao1'),mode:'ao1',slug:'change-limits',title:'Change definite limits',activityType:'question-set',microSkillIds:[skill('definite-limits')],vocabularyTags:substitutionVocabularyTags,implementationStep:64},
    {activityId:activity('complete-substitution','ao1'),mode:'ao1',slug:'complete-substitution',title:'Complete substitutions',activityType:'question-set',microSkillIds:[skill('indefinite-workflow'),skill('transform-integrand')],vocabularyTags:substitutionVocabularyTags,implementationStep:64},
    {activityId:activity('diagnose-errors','ao2'),mode:'ao2',slug:'diagnose-errors',title:'Diagnose substitution errors',activityType:'question-set',microSkillIds:[skill('error-diagnosis'),skill('mixed-variable-check'),skill('judge-substitution')],vocabularyTags:substitutionVocabularyTags,implementationStep:64},
    {activityId:activity('compare-recognition','ao2'),mode:'ao2',slug:'compare-recognition',title:'Recognition or substitution?',activityType:'question-set',microSkillIds:[skill('recognition-comparison')],vocabularyTags:substitutionVocabularyTags,implementationStep:64},
    {activityId:activity('unfamiliar-applications','ao3'),mode:'ao3',slug:'unfamiliar-applications',title:'Unfamiliar substitution applications',activityType:'question-set',microSkillIds:[skill('applications'),skill('choose-u'),skill('definite-limits')],vocabularyTags:substitutionVocabularyTags,implementationStep:64}
  ]
});
