import { defineTopicMetadata } from '../topic-metadata.js';
const prefix='y13:integration:areas';
const skill=s=>`skill:${prefix}:${s}`; const activity=(s,m='understand')=>`activity:${prefix}:${m}:${s}`;
export const year13AreasVocabularyTags=Object.freeze(['vocab:definite-integral','vocab:geometrical-area','vocab:signed-area','vocab:integration']);
export const year13AreasTopic=defineTopicMetadata({
 topicId:`topic:${prefix}`,scopeId:'y13-additional',strand:'integration',slug:'areas',title:'Areas with Year 13 techniques',sequence:330,
 modes:['understand','memorise','ao1','ao2','ao3'],prerequisiteTopicIds:['topic:y12:integration:area','topic:y12:integration:signed-area','topic:y13:integration:partial-fractions'],prerequisiteTags:['integration-as-area','signed-area','integration-method-selection'],vocabularyTags:year13AreasVocabularyTags,
 journey:[
  {id:'region',title:'Identify the region before integrating',summary:'Sketch, find intersections, set limits and decide which curve is on top.',microSkillIds:[skill('construct-region')],vocabularyTags:year13AreasVocabularyTags},
  {id:'split',title:'Split when top and bottom change',summary:'A single top-minus-bottom integral only works while the curve order is unchanged.',microSkillIds:[skill('split-region')],vocabularyTags:year13AreasVocabularyTags},
  {id:'geometry',title:'Choose geometry or calculus',summary:'Use exact geometry when it is simpler; otherwise construct the integral.',microSkillIds:[skill('geometry-vs-calculus')],vocabularyTags:year13AreasVocabularyTags},
  {id:'method',title:'Choose the integration technique last',summary:'After the region is correct, select from the full standard/reverse-chain/trig/substitution/parts/partial-fractions toolkit.',microSkillIds:[skill('method-selection')],vocabularyTags:year13AreasVocabularyTags}
 ],
 microSkills:[
  {microSkillId:skill('construct-region'),slug:'construct-region',title:'Find intersections, limits and top-minus-bottom order',prerequisiteTags:['integration-as-area'],vocabularyTags:year13AreasVocabularyTags,supportTargets:{understand:activity('construction-visual'),memorise:activity('construction-order','memorise'),ao1:activity('routine-between-curves','ao1')}},
  {microSkillId:skill('split-region'),slug:'split-region',title:'Split a region when curve order or sign changes',prerequisiteTags:['signed-area'],vocabularyTags:year13AreasVocabularyTags,supportTargets:{understand:activity('split-when-needed'),memorise:activity('split-rule','memorise'),ao1:activity('split-regions','ao1')}},
  {microSkillId:skill('geometry-vs-calculus'),slug:'geometry-vs-calculus',title:'Compare geometry and integration routes',prerequisiteTags:['integration-as-area'],vocabularyTags:year13AreasVocabularyTags,supportTargets:{understand:activity('geometry-or-calculus'),ao2:activity('compare-methods','ao2')}},
  {microSkillId:skill('method-selection'),slug:'method-selection',title:'Choose an integration method only after constructing the area integral',prerequisiteTags:['integration-method-selection'],vocabularyTags:year13AreasVocabularyTags,supportTargets:{understand:activity('full-toolkit'),memorise:activity('method-order','memorise'),ao3:activity('unfamiliar-diagrams','ao3')}},
  {microSkillId:skill('signed-vs-geometric'),slug:'signed-vs-geometric',title:'Explain signed integral versus geometrical area',prerequisiteTags:['signed-area'],vocabularyTags:year13AreasVocabularyTags,supportTargets:{understand:activity('signed-vs-geometric'),ao2:activity('signed-vs-geometric','ao2')}}
 ],
 activities:[
  ...[['construction-visual','Build the area before doing calculus'],['top-minus-bottom','Top minus bottom'],['split-when-needed','Split when the order changes'],['geometry-or-calculus','Geometry or calculus?'],['full-toolkit','Use the full integration toolkit'],['signed-vs-geometric','Signed integral vs geometrical area']].map(([slug,title])=>({activityId:activity(slug),mode:'understand',slug,title,activityType:'interactive',microSkillIds:[skill(slug==='split-when-needed'?'split-region':slug==='geometry-or-calculus'?'geometry-vs-calculus':slug==='full-toolkit'?'method-selection':slug==='signed-vs-geometric'?'signed-vs-geometric':'construct-region')],vocabularyTags:year13AreasVocabularyTags,implementationStep:67})),
  ...['construction-order','split-rule','geometry-cue','method-order','memory-games','mixed-review'].map((slug,i)=>({activityId:activity(slug,'memorise'),mode:'memorise',slug,title:['Region construction order','When to split','Geometry cue','Technique comes last','Memory games','Mixed review'][i],activityType:'memory',microSkillIds:[skill(['construct-region','split-region','geometry-vs-calculus','method-selection','construct-region','method-selection'][i])],vocabularyTags:year13AreasVocabularyTags,implementationStep:67})),
  {activityId:activity('routine-between-curves','ao1'),mode:'ao1',slug:'routine-between-curves',title:'Routine areas between curves',activityType:'question-set',microSkillIds:[skill('construct-region'),skill('method-selection')],vocabularyTags:year13AreasVocabularyTags,implementationStep:67},
  {activityId:activity('split-regions','ao1'),mode:'ao1',slug:'split-regions',title:'Split regions accurately',activityType:'question-set',microSkillIds:[skill('split-region')],vocabularyTags:year13AreasVocabularyTags,implementationStep:67},
  {activityId:activity('advanced-techniques','ao1'),mode:'ao1',slug:'advanced-techniques',title:'Areas with advanced integration techniques',activityType:'question-set',microSkillIds:[skill('method-selection')],vocabularyTags:year13AreasVocabularyTags,implementationStep:67},
  {activityId:activity('explain-splits','ao2'),mode:'ao2',slug:'explain-splits',title:'Explain add, subtract and split decisions',activityType:'question-set',microSkillIds:[skill('split-region')],vocabularyTags:year13AreasVocabularyTags,implementationStep:67},
  {activityId:activity('compare-methods','ao2'),mode:'ao2',slug:'compare-methods',title:'Compare geometry and calculus',activityType:'question-set',microSkillIds:[skill('geometry-vs-calculus')],vocabularyTags:year13AreasVocabularyTags,implementationStep:67},
  {activityId:activity('signed-vs-geometric','ao2'),mode:'ao2',slug:'signed-vs-geometric',title:'Interpret signed integral versus geometrical area',activityType:'question-set',microSkillIds:[skill('signed-vs-geometric')],vocabularyTags:year13AreasVocabularyTags,implementationStep:67},
  {activityId:activity('unfamiliar-diagrams','ao3'),mode:'ao3',slug:'unfamiliar-diagrams',title:'Construct solutions from unfamiliar diagrams',activityType:'question-set',microSkillIds:[skill('construct-region'),skill('method-selection')],vocabularyTags:year13AreasVocabularyTags,implementationStep:67}
 ]
});
