import { defineTopicMetadata } from '../topic-metadata.js';
const prefix='y13:integration:parametric-area';
const skill=s=>`skill:${prefix}:${s}`; const activity=(s,m='understand')=>`activity:${prefix}:${m}:${s}`;
export const parametricAreaVocabularyTags=Object.freeze(['vocab:parametric-equations','vocab:parameter','vocab:parameter-interval','vocab:differential','vocab:definite-integral','vocab:signed-area','vocab:geometrical-area','vocab:integration']);
export const parametricAreaTopic=defineTopicMetadata({
 topicId:`topic:${prefix}`,scopeId:'y13-additional',strand:'integration',slug:'parametric-area',title:'Area using parametric equations',sequence:340,
 modes:['understand','memorise','ao1','ao2','ao3'],prerequisiteTopicIds:['topic:y13:differentiation:parametric-differentiation','topic:y13:integration:areas','topic:y13:integration:substitution'],prerequisiteTags:['parametric-gradient','signed-area','integration-method-selection'],vocabularyTags:parametricAreaVocabularyTags,
 journey:[
  {id:'strip',title:'Build area from a thin vertical strip',summary:'Connect small area y Δx to Δx≈(dx/dt)Δt.',microSkillIds:[skill('thin-strip'),skill('formula')],vocabularyTags:parametricAreaVocabularyTags},
  {id:'limits',title:'Convert boundaries to t-limits',summary:'Map each x-boundary to the relevant t-value before evaluating the area.',microSkillIds:[skill('t-limits')],vocabularyTags:parametricAreaVocabularyTags},
  {id:'direction',title:'Make direction and sign visible',summary:'Use the sign of dx/dt to distinguish traversal direction, signed integral and geometrical area.',microSkillIds:[skill('direction'),skill('geometric-area')],vocabularyTags:parametricAreaVocabularyTags},
  {id:'method',title:'Choose any later integration technique last',summary:'After parametric setup, simplify the t-integral and then select the required integration method.',microSkillIds:[skill('later-technique')],vocabularyTags:parametricAreaVocabularyTags}
 ],
 microSkills:[
  {microSkillId:skill('thin-strip'),slug:'thin-strip',title:'Interpret a parametric vertical strip as y Δx',prerequisiteTags:['integration-as-area'],vocabularyTags:parametricAreaVocabularyTags,supportTargets:{understand:activity('thin-strip'),memorise:activity('thin-strip','memorise'),ao1:activity('formula-and-strip','ao1')}},
  {microSkillId:skill('formula'),slug:'formula',title:'Derive A=∫y(t)(dx/dt)dt',prerequisiteTags:['differential'],vocabularyTags:parametricAreaVocabularyTags,supportTargets:{understand:activity('derive-formula'),memorise:activity('formula','memorise'),ao1:activity('formula-and-strip','ao1')}},
  {microSkillId:skill('t-limits'),slug:'t-limits',title:'Convert x-boundaries to parameter limits',prerequisiteTags:['parameter-interval'],vocabularyTags:parametricAreaVocabularyTags,supportTargets:{understand:activity('convert-limits'),memorise:activity('limits','memorise'),ao1:activity('convert-limits','ao1')}},
  {microSkillId:skill('direction'),slug:'direction',title:'Interpret negative dx/dt and traversal direction',prerequisiteTags:['signed-area'],vocabularyTags:parametricAreaVocabularyTags,supportTargets:{understand:activity('direction-and-sign'),memorise:activity('direction','memorise'),ao2:activity('explain-direction','ao2')}},
  {microSkillId:skill('geometric-area'),slug:'geometric-area',title:'Adjust direction, reverse limits or split for geometrical area',prerequisiteTags:['signed-area'],vocabularyTags:parametricAreaVocabularyTags,supportTargets:{understand:activity('geometric-area'),ao1:activity('direction-and-area','ao1'),ao2:activity('diagnose-direction','ao2')}},
  {microSkillId:skill('later-technique'),slug:'later-technique',title:'Choose the later integration technique only after parametric setup',prerequisiteTags:['integration-method-selection'],vocabularyTags:parametricAreaVocabularyTags,supportTargets:{understand:activity('later-technique'),memorise:activity('sequence','memorise'),ao3:activity('mixed-technique','ao3')}}
 ],
 activities:[
  ...[['thin-strip','Thin vertical strip'],['derive-formula','From y dx to y(t)x′(t) dt'],['convert-limits','Convert x-boundaries to t-limits'],['direction-and-sign','Direction and negative dx/dt'],['geometric-area','Signed versus geometrical parametric area'],['later-technique','Parametric setup first, integration method second']].map(([slug,title])=>({activityId:activity(slug),mode:'understand',slug,title,activityType:'interactive',microSkillIds:[skill(slug==='derive-formula'?'formula':slug==='convert-limits'?'t-limits':slug==='direction-and-sign'?'direction':slug==='geometric-area'?'geometric-area':slug==='later-technique'?'later-technique':'thin-strip')],vocabularyTags:parametricAreaVocabularyTags,implementationStep:68})),
  ...['thin-strip','formula','limits','direction','sequence','memory-games','mixed-review'].map((slug,i)=>({activityId:activity(slug,'memorise'),mode:'memorise',slug,title:['Thin-strip meaning','Parametric area formula','Changing limits','Direction and sign','Setup sequence','Memory games','Mixed review'][i],activityType:'memory',microSkillIds:[skill(['thin-strip','formula','t-limits','direction','later-technique','formula','later-technique'][i])],vocabularyTags:parametricAreaVocabularyTags,implementationStep:68})),
  {activityId:activity('formula-and-strip','ao1'),mode:'ao1',slug:'formula-and-strip',title:'Use the parametric area formula',activityType:'question-set',microSkillIds:[skill('thin-strip'),skill('formula')],vocabularyTags:parametricAreaVocabularyTags,implementationStep:68},
  {activityId:activity('convert-limits','ao1'),mode:'ao1',slug:'convert-limits',title:'Convert boundaries to t-limits',activityType:'question-set',microSkillIds:[skill('t-limits')],vocabularyTags:parametricAreaVocabularyTags,implementationStep:68},
  {activityId:activity('direction-and-area','ao1'),mode:'ao1',slug:'direction-and-area',title:'Handle direction and geometrical area',activityType:'question-set',microSkillIds:[skill('direction'),skill('geometric-area')],vocabularyTags:parametricAreaVocabularyTags,implementationStep:68},
  {activityId:activity('explain-direction','ao2'),mode:'ao2',slug:'explain-direction',title:'Explain dx/dt and direction',activityType:'question-set',microSkillIds:[skill('formula'),skill('direction')],vocabularyTags:parametricAreaVocabularyTags,implementationStep:68},
  {activityId:activity('diagnose-direction','ao2'),mode:'ao2',slug:'diagnose-direction',title:'Diagnose limits and direction errors',activityType:'question-set',microSkillIds:[skill('t-limits'),skill('geometric-area')],vocabularyTags:parametricAreaVocabularyTags,implementationStep:68},
  {activityId:activity('bounded-regions','ao3'),mode:'ao3',slug:'bounded-regions',title:'Parametric regions bounded by axes and lines',activityType:'question-set',microSkillIds:[skill('formula'),skill('t-limits'),skill('geometric-area')],vocabularyTags:parametricAreaVocabularyTags,implementationStep:68},
  {activityId:activity('mixed-technique','ao3'),mode:'ao3',slug:'mixed-technique',title:'Parametric setup followed by another technique',activityType:'question-set',microSkillIds:[skill('later-technique')],vocabularyTags:parametricAreaVocabularyTags,implementationStep:68}
 ]
});
