/* Senior Maths Competition 2026 — browser OMR marker */
'use strict';
const APP={competition:'Senior Maths Competition 2026',form:'A',candidateMin:1,candidateMax:140,pageWmm:210,pageHmm:297,pxPerMm:6,qr:{x:164,y:252,w:25,h:25},fiducials:{TL:{x:10,y:281.5,size:5.5},TR:{x:194.5,y:281.5,size:5.5},BR:{x:194.5,y:10,size:5.5},BL:{x:10,y:10,size:5.5}},thresholds:{innerRadiusFraction:.66,pixelDark:205,blank:.075,marked:.22,ambiguityDelta:.075,moderate:.13,geometry:.035}};
APP.outW=Math.round(APP.pageWmm*APP.pxPerMm);APP.outH=Math.round(APP.pageHmm*APP.pxPerMm);APP.bubbles=buildBubbleTemplate();
const state={key:null,scoring:{start:25,correct:4,incorrect:-1,blank:0},roster:new Map(),scans:[],results:[],reviewLog:[],engineReady:false,processing:false};
const el=id=>document.getElementById(id);
window.addEventListener('DOMContentLoaded',init);
function init(){if(window.pdfjsLib)pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';bindUI();refreshKeyFromText();waitForOpenCV().then(()=>{state.engineReady=true;el('runtimeStatus').textContent='Marking engine ready';el('runtimeStatus').style.color='#1f6a48';updateMarkButton()}).catch(e=>{el('runtimeStatus').textContent='OpenCV failed to load';el('runtimeStatus').style.color='#9e2e2e';console.error(e)})}
function bindUI(){el('answerKeyText').addEventListener('input',refreshKeyFromText);el('answerKeyFile').addEventListener('change',handleKeyFile);['scoreStart','scoreCorrect','scoreIncorrect','scoreBlank'].forEach(id=>el(id).addEventListener('input',refreshScoring));el('rosterFile').addEventListener('change',handleRosterFile);el('scanFiles').addEventListener('change',e=>setScanFiles([...e.target.files]));const dz=el('dropZone');['dragenter','dragover'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.add('dragover')}));['dragleave','drop'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.remove('dragover')}));dz.addEventListener('drop',e=>setScanFiles([...e.dataTransfer.files]));el('markButton').addEventListener('click',processAll);el('clearButton').addEventListener('click',clearAll);el('exportXlsx').addEventListener('click',exportExcel);el('exportCsv').addEventListener('click',exportCsv)}
async function waitForOpenCV(timeoutMs=45000){const s=Date.now();while(Date.now()-s<timeoutMs){if(window.cv){if(typeof window.cv.then==='function'){try{window.cv=await window.cv}catch(_){}}if(window.cv&&window.cv.Mat)return}await sleep(120)}throw new Error('Timed out waiting for OpenCV.js')}
function buildBubbleTemplate(){const b={};for(let q=1;q<=25;q++){const left=q<=13,row=left?q-1:q-14,baseX=left?47.5:135.5,y=178.5-9.8*row;b[q]={};['A','B','C','D','E'].forEach((c,i)=>b[q][c]={x:baseX+12*i,y,r:2.55})}return b}
function parseKey(t){const a=String(t||'').toUpperCase().match(/[A-E]/g)||[];return a.length===25?Object.fromEntries(a.map((v,i)=>[i+1,v])):null}
function refreshKeyFromText(){state.key=parseKey(el('answerKeyText').value);const s=el('keyStatus');if(state.key){s.textContent='25 answers loaded';s.className='status-pill good'}else{const n=(el('answerKeyText').value.toUpperCase().match(/[A-E]/g)||[]).length;s.textContent=n?`${n}/25 answers`:'No key loaded';s.className=n?'status-pill warning':'status-pill neutral'}updateMarkButton()}
async function handleKeyFile(e){const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text()),a=d.answers||d,seq=Array.from({length:25},(_,i)=>String(a[String(i+1)]||a[i+1]||'').toUpperCase());if(!seq.every(x=>/^[A-E]$/.test(x)))throw new Error('JSON must contain answers 1–25 using A–E.');el('answerKeyText').value=seq.join(' ');if(d.scoring){if(Number.isFinite(Number(d.scoring.starting_score)))el('scoreStart').value=d.scoring.starting_score;if(Number.isFinite(Number(d.scoring.correct)))el('scoreCorrect').value=d.scoring.correct;if(Number.isFinite(Number(d.scoring.incorrect)))el('scoreIncorrect').value=d.scoring.incorrect;if(Number.isFinite(Number(d.scoring.blank)))el('scoreBlank').value=d.scoring.blank}refreshScoring();refreshKeyFromText()}catch(err){alert(`Could not load answer key: ${err.message}`)}}
function refreshScoring(){state.scoring={start:Number(el('scoreStart').value||0),correct:Number(el('scoreCorrect').value||0),incorrect:Number(el('scoreIncorrect').value||0),blank:Number(el('scoreBlank').value||0)};renderResults()}
async function handleRosterFile(e){const f=e.target.files[0];if(!f)return;try{const wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''}),map=new Map();rows.forEach(row=>{const n={};Object.entries(row).forEach(([k,v])=>n[String(k).trim().toLowerCase().replace(/_/g,' ')]=v);const id=normalizeId(pick(n,['candidate id','candidate','candidate number','id','number']));if(!id)return;map.set(id,{candidateId:id,name:String(pick(n,['name','student name','student'])||'').trim(),year:String(pick(n,['year','year group','grade'])||'').trim(),school:String(pick(n,['school','school name'])||'').trim()})});state.roster=map;el('rosterStatus').textContent=`${map.size} candidates loaded`;el('rosterStatus').className='status-pill good';renderResults()}catch(err){alert(`Could not read roster: ${err.message}`)}}
function pick(o,k){for(const x of k)if(o[x]!==undefined&&o[x]!=='')return o[x];return''}function normalizeId(v){const m=String(v??'').match(/\d+/);return m?String(Number(m[0])).padStart(3,'0'):''}
function setScanFiles(files){state.scans=files.filter(f=>/\.(pdf|png|jpe?g)$/i.test(f.name));const l=el('scanList');l.innerHTML='';state.scans.forEach(f=>{const c=document.createElement('span');c.className='file-chip';c.textContent=`${f.name} · ${formatBytes(f.size)}`;l.appendChild(c)});el('clearButton').disabled=state.scans.length===0&&state.results.length===0;updateMarkButton()}
function updateMarkButton(){el('markButton').disabled=!(state.engineReady&&state.key&&state.scans.length&&!state.processing)}
function clearAll(){state.scans=[];state.results=[];state.reviewLog=[];el('scanFiles').value='';el('scanList').innerHTML='';el('resultsSection').hidden=true;el('reviewSection').hidden=true;el('progressWrap').hidden=true;el('clearButton').disabled=true;updateMarkButton()}
