#!/usr/bin/env python3
from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
DIST = ROOT / "dist"

required = [
    SRC / "index.html",
    SRC / "diagram-primitives-demo.html",
    SRC / "linked-function-gradient-explorer-demo.html",
    SRC / "chord-to-tangent-explorer-demo.html",
    SRC / "family-of-curves-explorer-demo.html",
    SRC / "area-explorer-demo.html",
    SRC / "parametric-curve-tracer-demo.html",
    SRC / "rate-flow-diagram-demo.html",
    SRC / "rectangle-sum-explorer-demo.html",
    SRC / "trapezium-rule-builder-demo.html",
    SRC / "styles" / "tokens.css",
    SRC / "styles" / "app-shell.css",
    SRC / "styles" / "question-shell.css",
    SRC / "styles" / "memory-lab.css",
    SRC / "styles" / "diagram-primitives.css",
    SRC / "styles" / "pre-calculus-understand.css",
    SRC / "styles" / "first-principles-understand.css",
    SRC / "styles" / "tangents-normals-understand.css",
    SRC / "styles" / "stationary-points-understand.css",
    SRC / "styles" / "linked-function-gradient-explorer.css",
    SRC / "styles" / "chord-to-tangent-explorer.css",
    SRC / "styles" / "family-of-curves-explorer.css",
    SRC / "styles" / "area-explorer.css",
    SRC / "styles" / "signed-area-understand.css",
    SRC / "styles" / "product-quotient-chain-understand.css",
    SRC / "styles" / "trig-identities-inverse-understand.css",
    SRC / "styles" / "parametric-curve-tracer.css",
    SRC / "styles" / "rate-flow-diagram.css",
    SRC / "styles" / "rectangle-sum-explorer.css",
    SRC / "styles" / "trapezium-rule-builder.css",
    SRC / "styles" / "standard-integrals-understand.css",
    SRC / "scripts" / "app-shell.js",
    SRC / "scripts" / "navigation-route.js",
    SRC / "scripts" / "calculus-modelling-scaffold.js",
    SRC / "scripts" / "calculus-modelling-understand.js",
    SRC / "scripts" / "calculus-modelling-activities.js",
    SRC / "scripts" / "topic-content" / "calculus-modelling.js",
    SRC / "scripts" / "question-definitions" / "calculus-modelling-assessment.js",
    SRC / "styles" / "calculus-modelling.css",
    SRC / "scripts" / "standard-integrals-data.js",
    SRC / "scripts" / "standard-integrals-understand.js",
    SRC / "scripts" / "standard-integrals-activities.js",
    SRC / "scripts" / "partial-fractions-data.js",
    SRC / "scripts" / "partial-fractions-model.js",
    SRC / "scripts" / "partial-fractions-understand.js",
    SRC / "scripts" / "partial-fractions-activities.js",
    SRC / "scripts" / "topic-content" / "partial-fractions-integration.js",
    SRC / "scripts" / "question-definitions" / "partial-fractions-assessment.js",
    SRC / "styles" / "partial-fractions-understand.css",
    SRC / "scripts" / "topic-content" / "standard-integrals.js",
    SRC / "scripts" / "question-definitions" / "standard-integrals-assessment.js",
    SRC / "scripts" / "pre-calculus-understand.js",
    SRC / "scripts" / "pre-calculus-activities.js",
    SRC / "scripts" / "first-principles-understand.js",
    SRC / "scripts" / "first-principles-activities.js",
    SRC / "scripts" / "tangents-normals-understand.js",
    SRC / "scripts" / "tangents-normals-activities.js",
    SRC / "scripts" / "stationary-points-understand.js",
    SRC / "scripts" / "stationary-points-activities.js",
    SRC / "scripts" / "product-quotient-chain-understand.js",
    SRC / "scripts" / "product-quotient-chain-activities.js",
    SRC / "scripts" / "expression-structure-highlighter.js",
    SRC / "scripts" / "trig-identities-inverse-understand.js",
    SRC / "scripts" / "trig-identities-inverse-activities.js",
    SRC / "scripts" / "topic-content" / "trig-identities-inverse.js",
    SRC / "scripts" / "question-definitions" / "trig-identities-inverse-assessment.js",
    SRC / "scripts" / "topic-content" / "product-quotient-chain.js",
    SRC / "scripts" / "question-shell.js",
    SRC / "scripts" / "question-definition.js",
    SRC / "scripts" / "generator-runner.js",
    SRC / "scripts" / "hint-sequence.js",
    SRC / "scripts" / "solution-step.js",
    SRC / "scripts" / "question-feedback.js",
    SRC / "scripts" / "equation-step-renderer.js",
    SRC / "scripts" / "worked-solution-renderer.js",
    SRC / "scripts" / "question-catalogue.js",
    SRC / "scripts" / "diagnostic-router.js",
    SRC / "scripts" / "mastery-feedback-model.js",
    SRC / "scripts" / "classwiz-support-data.js",
    SRC / "scripts" / "classwiz-support-panel.js",
    SRC / "scripts" / "diagram-primitives.js",
    SRC / "scripts" / "diagram-primitives-demo.js",
    SRC / "scripts" / "linked-function-gradient-explorer.js",
    SRC / "scripts" / "linked-function-gradient-explorer-demo.js",
    SRC / "scripts" / "chord-to-tangent-explorer.js",
    SRC / "scripts" / "chord-to-tangent-explorer-demo.js",
    SRC / "scripts" / "family-of-curves-explorer.js",
    SRC / "scripts" / "family-of-curves-explorer-demo.js",
    SRC / "scripts" / "area-explorer.js",
    SRC / "scripts" / "signed-area-model.js",
    SRC / "scripts" / "signed-area-understand.js",
    SRC / "scripts" / "signed-area-activities.js",
    SRC / "scripts" / "topic-content" / "signed-area.js",
    SRC / "scripts" / "question-definitions" / "signed-area-assessment.js",
    SRC / "scripts" / "area-explorer-demo.js",
    SRC / "scripts" / "parametric-curve-tracer.js",
    SRC / "scripts" / "parametric-curve-tracer-demo.js",
    SRC / "scripts" / "rate-flow-diagram.js",
    SRC / "scripts" / "rate-flow-diagram-demo.js",
    SRC / "scripts" / "rectangle-sum-explorer.js",
    SRC / "scripts" / "rectangle-sum-explorer-demo.js",
    SRC / "scripts" / "trapezium-rule-builder.js",
    SRC / "scripts" / "trapezium-rule-builder-demo.js",
    SRC / "scripts" / "memory-item.js",
    SRC / "scripts" / "memory-content.js",
    SRC / "scripts" / "memory-game-content.js",
    SRC / "scripts" / "memory-review-content.js",
    SRC / "scripts" / "rapid-recall-engine.js",
    SRC / "scripts" / "diagram-recall-engine.js",
    SRC / "scripts" / "memory-mix-engine.js",
    SRC / "scripts" / "learn-view.js",
    SRC / "scripts" / "flashcard-engine.js",
    SRC / "scripts" / "match-engine.js",
    SRC / "scripts" / "build-rule-engine.js",
    SRC / "scripts" / "missing-piece-engine.js",
    SRC / "scripts" / "sort-engine.js",
    SRC / "scripts" / "impostor-engine.js",
    SRC / "scripts" / "memory-lab.js",
    SRC / "scripts" / "question-definitions" / "power-rule.js",
    SRC / "scripts" / "question-definitions" / "first-principles-assessment.js",
    SRC / "scripts" / "question-definitions" / "tangents-normals-assessment.js",
    SRC / "scripts" / "sample-activities.js",
    SRC / "scripts" / "scope-metadata.js",
    SRC / "scripts" / "topic-metadata.js",
    SRC / "scripts" / "topic-content" / "basics-differentiation.js",
    SRC / "scripts" / "topic-content" / "pre-calculus.js",
    SRC / "scripts" / "topic-content" / "first-principles.js",
    SRC / "scripts" / "topic-content" / "tangents-normals.js",
    SRC / "scripts" / "topic-content" / "stationary-points.js",
    SRC / "scripts" / "progress-model.js",
    SRC / "scripts" / "help-content.js",
    SRC / "scripts" / "vocabulary-data.js",
    SRC / "scripts" / "vocabulary-store.js",
    SRC / "scripts" / "vocabulary-term.js",
    SRC / "scripts" / "word-bank-model.js",
    SRC / "scripts" / "local-state-store.js",
    SRC / "scripts" / "progress-store.js",
    SRC / "scripts" / "app-state.js",
]
missing = [str(path.relative_to(ROOT)) for path in required if not path.exists()]
if missing:
    raise SystemExit(f"Missing source files: {', '.join(missing)}")

if DIST.exists():
    shutil.rmtree(DIST)
shutil.copytree(SRC, DIST)
print(f"Built static site: {DIST}")
